[package]
name = "move-it-cli"
version = "0.1.0"
authors = ["Thomas Kilian <Thomas-Kilian@gmx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
move-it = { path ="../move-it" }
