[package]
name = "move-it"
version = "0.1.0"
authors = ["Thomas Kilian <Thomas-Kilian@gmx.net>"]
edition = "2018"
description = "A library that moves files."
repository = "https://github.com/BigPapa314/move-it-ws/tree/master/move-it"
readme = "README.md"
keywords = ["files", "move", "copy"]
categories = ["Filesystem"]
license = "MIT OR Apache-2.0"

[dependencies]
